AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket for Lambda code storage'

Parameters:
  Environment:
    Description: Environment name
    Type: String
    Default: local
    AllowedValues:
      - local
      - prod

Resources:
  # S3 Bucket for Lambda Code
  LambdaCodeBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-lambda-code-bucket
        - Key: Environment
          Value: !Ref Environment

  # S3 Bucket for React App (https://github.com/chris-royall/portfolio-reactapp)
  ReactCodeBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-react-code-bucket
        - Key: Environment
          Value: !Ref Environment

Outputs:
  LambdaCodeBucketName:
    Description: Name of the S3 bucket containing Lambda code
    Value: !Ref LambdaCodeBucket
    Export:
      Name: !Sub ${AWS::StackName}-LambdaCodeBucketName
  
  ReactCodeBucketName:
    Description: Name of the S3 bucket containing React app code
    Value: !Ref ReactCodeBucket
    Export:
      Name: !Sub ${AWS::StackName}-ReactCodeBucketName
  
  ReactCodeBucketWebsiteURL:
    Description: URL for the S3 website hosting the React app
    Value: !GetAtt ReactCodeBucket.WebsiteURL
    Export:
      Name: !Sub ${AWS::StackName}-ReactCodeBucketWebsiteURL
