AWSTemplateFormatVersion: '2010-09-09'
Description: 'Portfolio infrastructure template with HTTP API Gateway and Lambda functions'

Parameters:
  Environment:
    Description: Environment name
    Type: String
    Default: local
    AllowedValues:
      - local
      - prod
  
  ExistingApiDomainName:
    Type: String
    Description: Existing API custom domain name
    Default: api.chrisroyall.com
    
  ThrottlingRateLimit:
    Type: Number
    Description: API throttling rate limit (requests per second)
    Default: 10
    
  ThrottlingBurstLimit:
    Type: Number
    Description: API throttling burst limit
    Default: 20
    
  ExistingAlarmsTopicName:
    Type: String
    Description: Name of existing SNS topic for alarms
    Default: Alarms
        
Resources:

  # DynamoDB Table for Projects
  ProjectsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-projects
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-projects
        - Key: Environment
          Value: !Ref Environment

  # Lambda IAM Role - shared by all Lambda functions
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Scan
                  - dynamodb:Query
                Resource: !GetAtt ProjectsTable.Arn
        - PolicyName: SESAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ses:SendEmail
                Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-lambda-role
        - Key: Environment
          Value: !Ref Environment

  # Contact Form Function
  ContactFormFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-contact-form
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.13
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              return {
                  'statusCode': 200,
                  'body': json.dumps('Placeholder function - update with make update-function')
              }
      Timeout: 10
      MemorySize: 128
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-contact-form
        - Key: Environment
          Value: !Ref Environment
      # Add reserved concurrency to prevent function from being overwhelmed
      ReservedConcurrentExecutions: 5

  # Contact Form CloudWatch Log Group
  ContactFormLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ContactFormFunction}
      RetentionInDays: 7
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-contact-form-logs
        - Key: Environment
          Value: !Ref Environment

  # Link Selection Function
  LinkSelectionFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-link-selection
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.13
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              return {
                  'statusCode': 200,
                  'body': json.dumps('Placeholder function - update with make update-function')
              }
      Timeout: 10
      MemorySize: 128
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-link-selection
        - Key: Environment
          Value: !Ref Environment
      # Add reserved concurrency to prevent function from being overwhelmed
      ReservedConcurrentExecutions: 5

  # Link Selection CloudWatch Log Group
  LinkSelectionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${LinkSelectionFunction}
      RetentionInDays: 7
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-link-selection-logs
        - Key: Environment
          Value: !Ref Environment

  # Projects Function
  ProjectsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-projects
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.13
      Environment:
        Variables:
          PROJECTS_TABLE: !Ref ProjectsTable
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              return {
                  'statusCode': 200,
                  'body': json.dumps('Placeholder function - update with make update-function')
              }
      Timeout: 10
      MemorySize: 128
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-projects
        - Key: Environment
          Value: !Ref Environment
      # Add reserved concurrency to prevent function from being overwhelmed
      ReservedConcurrentExecutions: 5

  # Projects CloudWatch Log Group
  ProjectsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ProjectsFunction}
      RetentionInDays: 7
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-projects-logs
        - Key: Environment
          Value: !Ref Environment

  # Combined API for all functions
  PortfolioApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub portfolio-api-${Environment}
      ProtocolType: HTTP
      DisableExecuteApiEndpoint: false
      Description: HTTP API for Portfolio Lambda Functions
      CorsConfiguration:
        AllowHeaders:
          - Content-Type
        AllowMethods:
          - GET
          - POST
        AllowOrigins:
          - 'http://localhost:5173'
          - 'https://chrisroyall.com'
          - 'https://www.chrisroyall.com'
        ExposeHeaders:
          - Content-Type
        MaxAge: 300
      Tags:
        Name: !Sub portfolio-api-${Environment}
        Environment: !Ref Environment

  # API Stage with throttling
  PortfolioApiStage:
    Type: AWS::ApiGatewayV2::Stage
    DependsOn: [ContactFormRoute, LinkSelectionRoute, ProjectsRoute]  # Ensure routes exist first
    Properties:
      ApiId: !Ref PortfolioApi
      StageName: "$default"
      AutoDeploy: true
      DefaultRouteSettings:
        ThrottlingRateLimit: !Ref ThrottlingRateLimit
        ThrottlingBurstLimit: !Ref ThrottlingBurstLimit
      RouteSettings:
        # Route-specific throttling for contact endpoint
        'POST /contact':
          ThrottlingRateLimit: 5
          ThrottlingBurstLimit: 10
        # Route-specific throttling for link endpoint
        'POST /link':
          ThrottlingRateLimit: 5
          ThrottlingBurstLimit: 10
        # Route-specific throttling for projects endpoint
        'GET /projects':
          ThrottlingRateLimit: 5
          ThrottlingBurstLimit: 10
      Tags:
        Name: !Sub portfolio-api-stage-${Environment}
        Environment: !Ref Environment

  # Contact Form Route
  ContactFormRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref PortfolioApi
      RouteKey: 'POST /contact'
      Target: !Sub integrations/${ContactFormIntegration}

  # Contact Form Integration
  ContactFormIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref PortfolioApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ContactFormFunction.Arn}/invocations
      PayloadFormatVersion: '2.0'
      IntegrationMethod: POST

  # Contact Form Lambda Permission
  ContactFormPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ContactFormFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${PortfolioApi}/*/POST/contact

  # Link Selection Route
  LinkSelectionRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref PortfolioApi
      RouteKey: 'POST /link'
      Target: !Sub integrations/${LinkSelectionIntegration}

  # Link Selection Integration
  LinkSelectionIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref PortfolioApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LinkSelectionFunction.Arn}/invocations
      PayloadFormatVersion: '2.0'
      IntegrationMethod: POST

  # Link Selection Lambda Permission
  LinkSelectionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LinkSelectionFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${PortfolioApi}/*/POST/link
      
  # Projects Route
  ProjectsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref PortfolioApi
      RouteKey: 'GET /projects'
      Target: !Sub integrations/${ProjectsIntegration}

  # Projects Integration
  ProjectsIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref PortfolioApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProjectsFunction.Arn}/invocations
      PayloadFormatVersion: '2.0'
      IntegrationMethod: POST

  # Projects Lambda Permission
  ProjectsPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ProjectsFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${PortfolioApi}/*/GET/projects

  # API Mapping to existing custom domain
  PortfolioApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    DependsOn: PortfolioApiStage
    Properties:
      ApiId: !Ref PortfolioApi
      DomainName: !Ref ExistingApiDomainName
      Stage: "$default"
      ApiMappingKey: !Sub "v1-${Environment}"

  # CloudWatch Alarm for Contact Form Function Errors
  ContactFormErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-contact-form-errors
      AlarmDescription: Alarm for Contact Form Lambda function errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 3600
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref ContactFormFunction
      AlarmActions:
        - !Sub arn:aws:sns:eu-west-2:${AWS::AccountId}:${ExistingAlarmsTopicName}

  # CloudWatch Alarm for Link Selection Function Errors
  LinkSelectionErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-link-selection-errors
      AlarmDescription: Alarm for Link Selection Lambda function errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 3600
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref LinkSelectionFunction
      AlarmActions:
        - !Sub arn:aws:sns:eu-west-2:${AWS::AccountId}:${ExistingAlarmsTopicName}

  # CloudWatch Alarm for Projects Function Errors
  ProjectsErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-projects-errors
      AlarmDescription: Alarm for Projects Lambda function errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 3600
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref ProjectsFunction
      AlarmActions:
        - !Sub arn:aws:sns:eu-west-2:${AWS::AccountId}:${ExistingAlarmsTopicName}

  # Metric Filters for Logged Errors
  ContactFormLogErrorFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref ContactFormLogGroup
      FilterPattern: "ERROR"
      MetricTransformations:
        - MetricNamespace: Portfolio/Lambda
          MetricName: ContactFormLoggedErrors
          MetricValue: "1"
          DefaultValue: 0

  LinkSelectionLogErrorFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref LinkSelectionLogGroup
      FilterPattern: "ERROR"
      MetricTransformations:
        - MetricNamespace: Portfolio/Lambda
          MetricName: LinkSelectionLoggedErrors
          MetricValue: "1"
          DefaultValue: 0

  ProjectsLogErrorFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref ProjectsLogGroup
      FilterPattern: "ERROR"
      MetricTransformations:
        - MetricNamespace: Portfolio/Lambda
          MetricName: ProjectsLoggedErrors
          MetricValue: "1"
          DefaultValue: 0

  # Alarms for Logged Errors
  ContactFormLoggedErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-contact-form-logged-errors
      AlarmDescription: Alarm for Contact Form Lambda logged errors
      MetricName: ContactFormLoggedErrors
      Namespace: Portfolio/Lambda
      Statistic: Sum
      Period: 3600
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Sub arn:aws:sns:eu-west-2:${AWS::AccountId}:${ExistingAlarmsTopicName}

  LinkSelectionLoggedErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-link-selection-logged-errors
      AlarmDescription: Alarm for Link Selection Lambda logged errors
      MetricName: LinkSelectionLoggedErrors
      Namespace: Portfolio/Lambda
      Statistic: Sum
      Period: 3600
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Sub arn:aws:sns:eu-west-2:${AWS::AccountId}:${ExistingAlarmsTopicName}

  ProjectsLoggedErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-projects-logged-errors
      AlarmDescription: Alarm for Projects Lambda logged errors
      MetricName: ProjectsLoggedErrors
      Namespace: Portfolio/Lambda
      Statistic: Sum
      Period: 3600
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Sub arn:aws:sns:eu-west-2:${AWS::AccountId}:${ExistingAlarmsTopicName}

  # Metric Filter for Button Clicked events
  LinkSelectionButtonClickedFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref LinkSelectionLogGroup
      FilterPattern: '{ $.button_clicked != "Page Loaded" }'
      MetricTransformations:
        - MetricNamespace: Portfolio/Traffic
          MetricName: ButtonClickedEvents
          MetricValue: "1"
          DefaultValue: 0

  # Alarm for Button Clicked events
  LinkSelectionButtonClickedAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-button-clicked-alarm
      AlarmDescription: Alarm when Button Clicked events are detected, expect "Page Loaded"
      MetricName: ButtonClickedEvents
      Namespace: Portfolio/Traffic
      Statistic: Sum
      Period: 3600
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${ExistingAlarmsTopicName}
              
Outputs:
  ApiEndpoint:
    Description: URL of the API Gateway endpoint
    Value: !Sub https://${PortfolioApi}.execute-api.${AWS::Region}.amazonaws.com/
    Export:
      Name: !Sub ${AWS::StackName}-ApiEndpoint
      
  ApiMappingPath:
    Description: Path mapping for the API on the custom domain
    Value: !Sub v1-${Environment}
    Export:
      Name: !Sub ${AWS::StackName}-ApiMappingPath
      
  ContactFormFunction:
    Description: Name of the Contact Form Lambda function
    Value: !Ref ContactFormFunction
    Export:
      Name: !Sub ${AWS::StackName}-ContactFormFunction
      
  LinkSelectionFunction:
    Description: Name of the Link Selection Lambda function
    Value: !Ref LinkSelectionFunction
    Export:
      Name: !Sub ${AWS::StackName}-LinkSelectionFunction

  ProjectsFunction:
    Description: Name of the Projects Lambda function
    Value: !Ref ProjectsFunction
    Export:
      Name: !Sub ${AWS::StackName}-ProjectsFunction
      
  ProjectsTable:
    Description: Name of the Projects DynamoDB table
    Value: !Ref ProjectsTable
    Export:
      Name: !Sub ${AWS::StackName}-ProjectsTable